### ISSUE TITLE
Использование в карточке lovelace

### ISSUE THREAD

**Issue by enselerizer** [AlexxIT/MorphNumbers#30]
Добрый день. Вопрос не столько касательно конкретно данного компонента, сколько в целом по фильтрам, но думаю что не я один данным вопросом задаюсь именно в контексте задачи, которую решает данный компонент.

Не нашел способов заставить использовать фильтр в карточке Lovelace, в том числе не помог и компонент config-template-card. 

Без фильтра работает:
```
type: custom:config-template-card
entities:
  - sensor.neboair_aqi
card:
    type: custom:mini-graph-card
    icon: mdi:forest
    name: AQI
    unit: ${42}

    ...
```

С фильтром не работает (ошибки никакой нет, но карточка пропадает вовсе):
```
type: custom:config-template-card
entities:
  - sensor.neboair_aqi
card:
    type: custom:mini-graph-card
    icon: mdi:forest
    name: AQI
    unit: ${42|format(morph='градус')}

    ...
```

Если фильтр возможно заставить работать в карточке, прошу поделиться опытом.
